const generateSCSSString = (singleVar: string, groupName: string, groupVar: string) => {
  const scssString = `/** THIS IS AN AUTOGENERATED FILE **/\n\n $${singleVar};\n\n $${groupName}: (${groupVar});`;

  return scssString;
};

export default generateSCSSString;
